package policy

import (
	"bytes"
	"encoding/base64"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"strings"
	"testing"

	"google.golang.org/protobuf/proto"

	morphgatev1 "morphgate/control-plane/gen/morphgate/v1"
)

// The cross-language policy IR conformance suite (docs/impl/phase1-spec.md
// §5.8). cases.json is hand-written; cases.ir.json is generated by this test
// with -update and committed. The Rust side
// (proto/rust/tests/policy_ir_conformance.rs) decodes the same IR bytes and
// must reach the same expectations.

var updateIR = flag.Bool("update", false, "rewrite testdata/policy-ir/cases.ir.json from the compiler")

const (
	conformanceCasesPath = "../../../testdata/policy-ir/cases.json"
	conformanceIRPath    = "../../../testdata/policy-ir/cases.ir.json"
	conformanceGenerator = "control-plane/internal/policy (cel-go v0.30.0)"
	minConformanceCases  = 150
)

type conformanceFile struct {
	Version  int                           `json:"version"`
	Lists    map[string][]string           `json:"lists"`
	Contexts map[string]conformanceContext `json:"contexts"`
	Cases    []conformanceCase             `json:"cases"`
}

type conformanceContext struct {
	Input   json.RawMessage `json:"input"`
	Missing []string        `json:"missing"`
}

type conformanceCase struct {
	Name         string `json:"name"`
	Expr         string `json:"expr"`
	Context      string `json:"context"`
	Expect       string `json:"expect,omitempty"`
	CompileError string `json:"compile_error,omitempty"`
}

type conformanceIRFile struct {
	Version   int                 `json:"version"`
	IRVersion int                 `json:"ir_version"`
	Generator string              `json:"generator"`
	Cases     []conformanceIRCase `json:"cases"`
}

type conformanceIRCase struct {
	Name string `json:"name"`
	IR   string `json:"ir"`
}

func decodeStrict(data []byte, v any) error {
	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	if err := dec.Decode(v); err != nil {
		return err
	}
	if dec.More() {
		return fmt.Errorf("trailing data after the JSON value")
	}
	return nil
}

// loadConformance reads cases.json and validates its structure.
func loadConformance(t *testing.T) (*conformanceFile, map[string]*Input) {
	t.Helper()
	data, err := os.ReadFile(conformanceCasesPath)
	if err != nil {
		t.Fatal(err)
	}
	var f conformanceFile
	if err := decodeStrict(data, &f); err != nil {
		t.Fatalf("cases.json: %v", err)
	}
	if f.Version != 1 {
		t.Fatalf("cases.json version = %d, want 1", f.Version)
	}
	inputs := make(map[string]*Input, len(f.Contexts))
	for name, c := range f.Contexts {
		in := &Input{}
		if err := decodeStrict(c.Input, in); err != nil {
			t.Fatalf("context %s: input is not Activation JSON (spec §4.2): %v", name, err)
		}
		inputs[name] = in
		for _, p := range c.Missing {
			if !isSchemaPath(p) {
				t.Errorf("context %s: MISSING path %q is not a schema path (spec §4.3)", name, p)
			}
		}
	}
	seen := map[string]bool{}
	for _, c := range f.Cases {
		switch {
		case c.Name == "" || seen[c.Name]:
			t.Errorf("case name %q is empty or duplicated", c.Name)
		case c.Expr == "":
			t.Errorf("case %s has no expr", c.Name)
		case inputs[c.Context] == nil:
			t.Errorf("case %s: unknown context %q", c.Name, c.Context)
		case (c.Expect == "") == (c.CompileError == ""):
			t.Errorf("case %s: exactly one of expect and compile_error is required", c.Name)
		case c.Expect != "" && !slices.Contains([]string{"true", "false", "unknown", "error"}, c.Expect):
			t.Errorf("case %s: expect %q is not true | false | unknown | error", c.Name, c.Expect)
		}
		seen[c.Name] = true
	}
	if len(f.Cases) < minConformanceCases {
		t.Errorf("cases.json has %d cases, spec §5.8 requires >= %d", len(f.Cases), minConformanceCases)
	}
	return &f, inputs
}

// compileCase compiles one conformance expression as a rule.
func compileCase(t *testing.T, c conformanceCase) (*CheckedRule, Diagnostics) {
	t.Helper()
	r := &Rule{ID: "case", Phase: "bot", Expr: c.Expr, Action: "log", Mode: DefaultMode, Rollout: DefaultRollout, File: c.Name}
	checked, diags := newTestCompiler(t, Options{}).Check([]*Rule{r})
	if len(checked) > 1 {
		t.Fatalf("%s: %d rules compiled", c.Name, len(checked))
	}
	if len(checked) == 0 {
		return nil, diags
	}
	return checked[0], diags
}

// TestIRConformance is spec §5.8 "Go": compile every case, compare the IR
// bytes with cases.ir.json (rewritten with -update), and evaluate with the
// cel-go reference Evaluator. It additionally runs the IR through irInterp,
// an independent Go implementation of the §5.3 semantics, which must agree
// with the reference and never spend more steps than max_steps.
func TestIRConformance(t *testing.T) {
	f, inputs := loadConformance(t)
	ev, err := NewEvaluator(f.Lists)
	if err != nil {
		t.Fatal(err)
	}

	want := conformanceIRFile{Version: 1, IRVersion: IRVersion, Generator: conformanceGenerator, Cases: []conformanceIRCase{}}
	outcomes := map[string]map[string]bool{}
	for _, c := range f.Cases {
		cr, diags := compileCase(t, c)
		if c.CompileError != "" {
			if cr != nil || !diags.HasErrors() {
				t.Errorf("%s: %q compiled, want an error containing %q", c.Name, c.Expr, c.CompileError)
				continue
			}
			if !slices.ContainsFunc(diags.Errors(), func(d Diagnostic) bool { return strings.Contains(d.Message, c.CompileError) }) {
				t.Errorf("%s: no error contains %q; got:\n  %s", c.Name, c.CompileError, strings.Join(diagStrings(diags), "\n  "))
			}
			continue
		}
		if cr == nil || diags.HasErrors() {
			t.Errorf("%s: %q does not compile:\n  %s", c.Name, c.Expr, strings.Join(diagStrings(diags), "\n  "))
			continue
		}
		for _, name := range cr.Lists {
			if _, ok := f.Lists[name]; !ok {
				t.Errorf("%s: list(%q) is not defined in cases.json lists (the Rust decoder rejects unknown lists)", c.Name, name)
			}
		}
		want.Cases = append(want.Cases, conformanceIRCase{Name: c.Name, IR: base64.StdEncoding.EncodeToString(cr.ExprIR)})

		in, missing := inputs[c.Context], f.Contexts[c.Context].Missing
		res, raw, err := ev.evaluate(cr, in, missing, 0)
		if err != nil {
			t.Errorf("%s: %v", c.Name, err)
			continue
		}
		if res.String() != c.Expect {
			t.Errorf("%s: cel-go reference = %s (%v), want %s\n  expr: %s", c.Name, res, raw, c.Expect, c.Expr)
		}
		if res == ResultUnknown {
			requireUnderMissing(t, c.Name+" (cel-go)", unknownPaths(raw), missing)
		}

		// Decode the committed bytes, not the in-memory message, as the Edge does.
		var pe morphgatev1.PolicyExpr
		if err := proto.Unmarshal(cr.ExprIR, &pe); err != nil {
			t.Fatalf("%s: %v", c.Name, err)
		}
		if pe.GetIrVersion() != IRVersion || pe.GetMaxSteps() != MaxSteps(pe.GetRoot()) || pe.GetMaxSteps() > MaxIRSteps {
			t.Errorf("%s: ir_version %d, max_steps %d (recomputed %d)", c.Name, pe.GetIrVersion(), pe.GetMaxSteps(), MaxSteps(pe.GetRoot()))
		}
		it := &irInterp{in: in, missing: missing, lists: f.Lists, outcomes: outcomes}
		got, paths := it.evalRule(&pe)
		if got != c.Expect {
			t.Errorf("%s: IR interpreter = %s, want %s\n  expr: %s", c.Name, got, c.Expect, c.Expr)
		}
		if got == "unknown" {
			requireUnderMissing(t, c.Name+" (IR)", paths, missing)
		}
		if it.steps > pe.GetMaxSteps() {
			t.Errorf("%s: evaluation took %d steps, more than max_steps %d", c.Name, it.steps, pe.GetMaxSteps())
		}
	}

	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "  ")
	if err := enc.Encode(want); err != nil {
		t.Fatal(err)
	}
	if *updateIR {
		if err := os.WriteFile(conformanceIRPath, buf.Bytes(), 0o644); err != nil {
			t.Fatal(err)
		}
		t.Logf("wrote %s (%d cases)", conformanceIRPath, len(want.Cases))
	} else {
		committed, err := os.ReadFile(conformanceIRPath)
		if err != nil {
			t.Fatalf("%v (run go test ./internal/policy -run TestIRConformance -update)", err)
		}
		if !bytes.Equal(committed, buf.Bytes()) {
			t.Errorf("%s is stale: the compiler now emits different IR (run go test ./internal/policy -run TestIRConformance -update and review the diff)", conformanceIRPath)
		}
	}

	requireOutcomeCoverage(t, outcomes)
}

func requireUnderMissing(t *testing.T, name string, paths, missing []string) {
	t.Helper()
	if len(paths) == 0 {
		t.Errorf("%s: unknown result without paths", name)
	}
	for _, p := range paths {
		if !isMissing(p, missing) {
			t.Errorf("%s: unknown path %q is not under a MISSING path %v", name, p, missing)
		}
	}
}

// requireOutcomeCoverage checks the §5.8 coverage requirement "every IR node
// kind with true / false / unknown / error where applicable" on the nodes the
// IR interpreter actually evaluated.
func requireOutcomeCoverage(t *testing.T, outcomes map[string]map[string]bool) {
	t.Helper()
	predicate := []string{"true", "false", "unknown", "error"}
	want := map[string][]string{
		"literal":     {"true", "false", "value"},
		"field":       {"true", "false", "value", "unknown"},
		"has":         {"true", "false"},
		"list":        {"value", "unknown", "error"},
		"not":         predicate,
		"and":         predicate,
		"or":          predicate,
		"cond":        {"true", "false", "value", "unknown", "error"},
		"compare":     predicate,
		"in_list":     predicate,
		"in_map":      predicate,
		"index_map":   {"value", "unknown", "error"},
		"size":        {"value", "unknown", "error"},
		"string_call": predicate,
		"ip_in":       predicate,
		"named_list":  {"value"},
		"glob":        predicate,
	}
	for kind, outs := range want {
		for _, o := range outs {
			if !outcomes[kind][o] {
				t.Errorf("coverage: no case evaluates a %s node to %s (spec §5.8)", kind, o)
			}
		}
	}
	if got := outcomes["has"]; got["unknown"] || got["error"] {
		t.Errorf("has() must never be unknown or error: %v", got)
	}
}

// TestIRConformanceCoversPolicyFiles: every expression of docs/06 §2 and of
// control-plane/testdata/policies/valid/*.yaml has a matching and a
// non-matching conformance case (spec §5.8).
func TestIRConformanceCoversPolicyFiles(t *testing.T) {
	f, _ := loadConformance(t)
	space := regexp.MustCompile(`\s+`)
	norm := func(s string) string { return space.ReplaceAllString(strings.TrimSpace(s), " ") }
	expects := map[string]map[string]bool{}
	for _, c := range f.Cases {
		if c.Expect == "" {
			continue
		}
		e := norm(c.Expr)
		if expects[e] == nil {
			expects[e] = map[string]bool{}
		}
		expects[e][c.Expect] = true
	}
	files, err := filepath.Glob("../../testdata/policies/valid/*.yaml")
	if err != nil || len(files) == 0 {
		t.Fatalf("no valid policy files: %v", err)
	}
	for _, file := range files {
		rules, diags := ParseFile(file)
		if diags.HasErrors() {
			t.Fatalf("%s: %v", file, diagStrings(diags))
		}
		for _, r := range rules {
			got := expects[norm(r.Expr)]
			if !got["true"] || !got["false"] {
				t.Errorf("%s: rule %s needs a true and a false case in cases.json (has %v)", filepath.Base(file), r.ID, got)
			}
		}
	}
}

// TestIRConformanceSpecNames pins the case names and required constructs the
// spec quotes (§5.8), so that the Rust suite can refer to them.
func TestIRConformanceSpecNames(t *testing.T) {
	f, _ := loadConformance(t)
	byName := map[string]conformanceCase{}
	byExpr := map[string]conformanceCase{}
	for _, c := range f.Cases {
		byName[c.Name] = c
		byExpr[c.Expr] = c
	}
	for name, want := range map[string]conformanceCase{
		"docs06.block-impersonators.match": {Expr: `risk.class == "IMPERSONATOR"`, Context: "cf_impersonator", Expect: "true"},
		"missing.and.false-absorbs":        {Expr: `false && tls.version == "TLSv1.3"`, Context: "cf_browser", Expect: "false"},
		"reject.arith":                     {Expr: `risk.score + 1 > 2`, Context: "cf_browser", CompileError: "unsupported in policy IR"},
	} {
		want.Name = name
		if byName[name] != want {
			t.Errorf("case %s = %+v, want %+v", name, byName[name], want)
		}
	}
	for _, expr := range []string{`1 in [1.0, "a"]`, `1 in [1.0]`, `"a" in [1, "a"]`, `[1, 2.0] == [1, 2.0]`, `[[1]] == [[1]]`} {
		if c, ok := byExpr[expr]; !ok || c.CompileError == "" {
			t.Errorf("spec §5.8 requires a compile_error case for %s", expr)
		}
	}
	if c := byName["steps.near-bound"]; c.Expect == "" {
		t.Error("missing the near-bound step case")
	}
	if c := byName["reject.steps.glob-chain"]; !strings.Contains(c.CompileError, "evaluation step bound") {
		t.Error("missing the over-bound step case")
	}
}

// TestIRConformanceGenerator keeps the generator string of cases.ir.json in
// step with the cel-go version in go.mod.
func TestIRConformanceGenerator(t *testing.T) {
	gomod, err := os.ReadFile("../../go.mod")
	if err != nil {
		t.Fatal(err)
	}
	m := regexp.MustCompile(`github\.com/google/cel-go (v\S+)`).FindSubmatch(gomod)
	if m == nil || !strings.Contains(conformanceGenerator, "cel-go "+string(m[1])+")") {
		t.Errorf("generator %q does not name the cel-go version in go.mod (%s)", conformanceGenerator, m)
	}
}
