//! Cross-language bundle check (docs/impl/phase1-spec.md §16 "跨语言签名",
//! §2.1): the golden bundles that WP-G2's Go builder and signer write
//! (`control-plane/testdata/sites/golden/`, regenerated by
//! `go test ./internal/bundle -run TestGolden -update`) pass the Edge's
//! `verify_bundle` with the owner test key, and every compiled rule of
//! `golden-rules.bundle` (IR from WP-G1's compiler) converts with
//! `mg_proto::ir::rule_from_proto` (WP-R1), including the recomputed
//! `max_steps`. WP-E1a's `edge/tests/bundle_load.rs` repeats this through the
//! full site runtime.

use mg_core::policy::NamedLists;
use mg_edge_core::bundle::{OwnerKeys, VerifiedBundle, verify_bundle};
use mg_proto::ir::rule_from_proto;
use std::collections::BTreeMap;
use std::path::PathBuf;

fn repo(path: &str) -> Vec<u8> {
    let p = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join(path);
    std::fs::read(&p).unwrap_or_else(|e| panic!("{}: {e}", p.display()))
}

fn owner_keys() -> OwnerKeys {
    OwnerKeys::from_pub_files(&[(
        "owner-test.pub",
        &repo("testdata/phase1/keys/owner-test.pub"),
    )])
    .unwrap()
}

fn verify(name: &str) -> VerifiedBundle {
    let bytes = repo(&format!("control-plane/testdata/sites/golden/{name}"));
    let hosts = ["example.com", "www.example.com", "staging.example.com"].map(String::from);
    verify_bundle(&bytes, &owner_keys(), "blog", &hosts).unwrap_or_else(|e| panic!("{name}: {e}"))
}

#[test]
fn golden_norules_bundle_verifies() {
    let v = verify("golden-norules.bundle");
    assert_eq!(v.bundle.site_id, "blog");
    assert!(
        v.bundle.environments.iter().all(|e| e.rules.is_empty()),
        "the no-rules golden bundle has rules"
    );
}

#[test]
fn golden_rules_bundle_verifies_and_every_rule_converts() {
    let v = verify("golden-rules.bundle");
    let lists = NamedLists::new(
        v.bundle
            .lists
            .iter()
            .map(|(name, l)| (name.clone(), l.entries.clone()))
            .collect::<BTreeMap<_, _>>(),
    );
    let mut converted = 0;
    for env in &v.bundle.environments {
        for r in &env.rules {
            let rule = rule_from_proto(r, &lists)
                .unwrap_or_else(|e| panic!("{} / {}: {e}", env.name, r.id));
            assert_eq!(rule.id, r.id);
            converted += 1;
        }
    }
    assert!(converted > 0, "golden-rules.bundle carries no rules");
}
