//! Cross-language policy IR conformance (docs/impl/phase1-spec.md §5.8).
//!
//! `testdata/policy-ir/cases.json` (hand-written) and `cases.ir.json`
//! (generated by the Go compiler, `go test ./internal/policy -run
//! TestIRConformance -update`) are owned by WP-G1. This test decodes every IR
//! with `mg_proto::ir::decode_program` (which recomputes `max_steps` and
//! compares it with the compiler's value), builds the Activation and the
//! MissingSet of the case's context, evaluates, and checks the expectation;
//! `unknown` results must name MISSING paths only, and no evaluation may
//! spend more steps than the static bound.
//!
//! WP-G1 and WP-R1 have both landed, so missing fixtures fail the test
//! (§2.1: "both merged -> must be green"); the harness itself is also
//! exercised on a fixture generated here.

use base64::Engine as _;
use mg_core::policy::{Activation, EvalResult, MissingSet, NamedLists, Program, eval_steps};
use mg_proto::ir::decode_program;
use mg_proto::v1;
use prost::Message;
use serde_json::Value;
use std::collections::{BTreeMap, HashMap};
use std::path::{Path, PathBuf};

/// One case of `cases.json`.
struct Case {
    name: String,
    expr: String,
    context: String,
    expect: Option<String>,
    compile_error: bool,
}

/// Outcome of a whole suite run.
#[derive(Debug, Default)]
struct Report {
    evaluated: usize,
    failures: Vec<String>,
}

fn expect_of(r: &EvalResult) -> &'static str {
    match r {
        EvalResult::True => "true",
        EvalResult::False => "false",
        EvalResult::Unknown(_) => "unknown",
        EvalResult::Error(_) => "error",
    }
}

fn str_field(v: &Value, key: &str) -> Result<String, String> {
    v.get(key)
        .and_then(Value::as_str)
        .map(str::to_string)
        .ok_or_else(|| format!("missing string {key:?} in {v}"))
}

fn parse_cases(doc: &Value) -> Result<Vec<Case>, String> {
    doc["cases"]
        .as_array()
        .ok_or("cases.json: no cases array")?
        .iter()
        .map(|c| {
            Ok(Case {
                name: str_field(c, "name")?,
                expr: str_field(c, "expr")?,
                context: str_field(c, "context")?,
                expect: c.get("expect").and_then(Value::as_str).map(str::to_string),
                compile_error: c.get("compile_error").is_some(),
            })
        })
        .collect()
}

/// Runs the suite in `dir` (`cases.json` + `cases.ir.json`).
fn run_suite(dir: &Path) -> Result<Report, String> {
    let read = |name: &str| -> Result<Value, String> {
        let text = std::fs::read_to_string(dir.join(name)).map_err(|e| format!("{name}: {e}"))?;
        serde_json::from_str(&text).map_err(|e| format!("{name}: {e}"))
    };
    let cases_doc = read("cases.json")?;
    let ir_doc = read("cases.ir.json")?;
    if cases_doc["version"] != 1 || ir_doc["version"] != 1 || ir_doc["ir_version"] != 1 {
        return Err("unsupported fixture version".into());
    }
    let lists: BTreeMap<String, Vec<String>> =
        serde_json::from_value(cases_doc["lists"].clone()).map_err(|e| format!("lists: {e}"))?;
    let lists = NamedLists::new(lists);
    let cases = parse_cases(&cases_doc)?;

    let mut report = Report::default();
    let mut contexts: HashMap<String, (Activation, MissingSet)> = HashMap::new();
    for (name, c) in cases_doc["contexts"]
        .as_object()
        .ok_or("cases.json: no contexts object")?
    {
        let act: Activation = match serde_json::from_value(c["input"].clone()) {
            Ok(a) => a,
            Err(e) => {
                report
                    .failures
                    .push(format!("context {name}: not Activation JSON (§4.2): {e}"));
                continue;
            }
        };
        let missing: Vec<String> = serde_json::from_value(c["missing"].clone()).unwrap_or_default();
        match MissingSet::new(&missing) {
            Ok(m) => {
                contexts.insert(name.clone(), (act, m));
            }
            Err(e) => report.failures.push(format!("context {name}: {e}")),
        }
    }

    // The IR file lists exactly the cases without compile_error, in order.
    let irs: Vec<(String, String)> = ir_doc["cases"]
        .as_array()
        .ok_or("cases.ir.json: no cases array")?
        .iter()
        .map(|c| Ok((str_field(c, "name")?, str_field(c, "ir")?)))
        .collect::<Result<_, String>>()?;
    let want: Vec<&str> = cases
        .iter()
        .filter(|c| !c.compile_error)
        .map(|c| c.name.as_str())
        .collect();
    let got: Vec<&str> = irs.iter().map(|(n, _)| n.as_str()).collect();
    if want != got {
        report.failures.push(format!(
            "cases.ir.json does not list the non-compile_error cases of cases.json in order \
             ({} vs {} entries)",
            got.len(),
            want.len()
        ));
    }
    let by_name: HashMap<&str, &Case> = cases.iter().map(|c| (c.name.as_str(), c)).collect();

    for (name, ir) in &irs {
        let Some(case) = by_name.get(name.as_str()) else {
            report.failures.push(format!("{name}: not in cases.json"));
            continue;
        };
        let fail = |msg: String| format!("{} ({}): {msg}", case.name, case.expr);
        let Some(expect) = case.expect.as_deref() else {
            report.failures.push(fail("has IR but no expect".into()));
            continue;
        };
        let bytes = match base64::engine::general_purpose::STANDARD.decode(ir) {
            Ok(b) => b,
            Err(e) => {
                report.failures.push(fail(format!("bad base64: {e}")));
                continue;
            }
        };
        let program: Program = match decode_program(&bytes, &lists) {
            Ok(p) => p,
            Err(e) => {
                report
                    .failures
                    .push(fail(format!("rejected by decode_program: {e}")));
                continue;
            }
        };
        let Some((act, missing)) = contexts.get(&case.context) else {
            report
                .failures
                .push(fail(format!("unknown context {}", case.context)));
            continue;
        };
        let (result, steps) = eval_steps(&program, act, missing, &lists);
        report.evaluated += 1;
        if expect_of(&result) != expect {
            report
                .failures
                .push(fail(format!("expected {expect}, got {result:?}")));
        }
        let bad_unknown = match &result {
            EvalResult::Unknown(paths) => {
                paths.is_empty() || !paths.iter().all(|p| missing.is_missing(p))
            }
            _ => false,
        };
        if bad_unknown {
            report
                .failures
                .push(fail(format!("unknown paths of {result:?} not all MISSING")));
        }
        if steps > program.max_steps() {
            report.failures.push(fail(format!(
                "spent {steps} steps, static bound {}",
                program.max_steps()
            )));
        }
    }
    Ok(report)
}

fn fixture_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../testdata/policy-ir")
}

/// §5.8: the committed Go fixtures, case for case.
#[test]
fn go_fixtures_conform() {
    let dir = fixture_dir();
    assert!(
        dir.join("cases.json").exists() && dir.join("cases.ir.json").exists(),
        "testdata/policy-ir/cases.json and cases.ir.json are required (WP-G1, §5.8)"
    );
    let report = run_suite(&dir).unwrap_or_else(|e| panic!("{e}"));
    assert!(
        report.failures.is_empty(),
        "{} of {} conformance cases failed:\n{}",
        report.failures.len(),
        report.evaluated,
        report.failures.join("\n")
    );
    assert!(report.evaluated > 0, "no IR cases evaluated");
    println!(
        "policy IR conformance: {} cases evaluated",
        report.evaluated
    );
}

// --- harness self-test on a generated fixture -------------------------------------

fn node(k: v1::expr::Kind) -> v1::Expr {
    v1::Expr { kind: Some(k) }
}

fn s(v: &str) -> v1::Expr {
    node(v1::expr::Kind::Literal(v1::Literal {
        value: Some(v1::literal::Value::StringValue(v.into())),
    }))
}

fn field(p: &str) -> v1::Expr {
    node(v1::expr::Kind::Field(p.into()))
}

fn eq(l: v1::Expr, r: v1::Expr) -> v1::Expr {
    node(v1::expr::Kind::Compare(Box::new(v1::Compare {
        op: v1::CompareOp::Eq as i32,
        lhs: Some(Box::new(l)),
        rhs: Some(Box::new(r)),
    })))
}

fn ip_in(l: v1::Expr, list: &str) -> v1::Expr {
    node(v1::expr::Kind::IpIn(Box::new(v1::Binary {
        lhs: Some(Box::new(l)),
        rhs: Some(Box::new(node(v1::expr::Kind::NamedList(list.into())))),
    })))
}

/// Encodes `root` with its recomputed step bound (the Go compiler's job).
fn encode(root: v1::Expr, lists: &NamedLists) -> String {
    let mut p = v1::PolicyExpr {
        ir_version: 1,
        root: Some(root),
        fields: vec![],
        max_steps: 0,
    };
    if let Err(mg_proto::ir::IrError::Steps { computed, .. }) =
        mg_proto::ir::program_from_proto(&p, lists)
    {
        p.max_steps = computed;
    }
    base64::engine::general_purpose::STANDARD.encode(p.encode_to_vec())
}

fn write_fixture(dir: &Path, cases: serde_json::Value, irs: serde_json::Value) {
    std::fs::create_dir_all(dir).unwrap();
    std::fs::write(dir.join("cases.json"), cases.to_string()).unwrap();
    std::fs::write(dir.join("cases.ir.json"), irs.to_string()).unwrap();
}

fn temp_dir(tag: &str) -> PathBuf {
    std::env::temp_dir().join(format!(
        "mg-policy-ir-conformance-{tag}-{}",
        std::process::id()
    ))
}

#[test]
fn harness_runs_a_generated_fixture() {
    let lists_json = serde_json::json!({"owner_cidrs": ["10.0.0.0/8"], "broken": ["bogus"]});
    let lists = NamedLists::new(serde_json::from_value(lists_json.clone()).unwrap());
    let cases = serde_json::json!({
        "version": 1,
        "lists": lists_json,
        "contexts": {
            "cf_browser": {
                "input": {"req": {"method": "GET"}, "net": {"ip": "10.1.2.3"}},
                "missing": ["tls", "http.header_order", "identity.proof", "identity.agent"]
            }
        },
        "cases": [
            {"name": "method", "expr": "req.method == \"GET\"", "context": "cf_browser", "expect": "true"},
            {"name": "owner", "expr": "ip_in(net.ip, list(\"owner_cidrs\"))", "context": "cf_browser", "expect": "true"},
            {"name": "tls", "expr": "tls.version == \"TLSv1.3\"", "context": "cf_browser", "expect": "unknown"},
            {"name": "broken", "expr": "ip_in(net.ip, list(\"broken\"))", "context": "cf_browser", "expect": "error"},
            {"name": "arith", "expr": "risk.score + 1 > 2", "context": "cf_browser", "compile_error": "unsupported in policy IR"}
        ]
    });
    let irs = serde_json::json!({
        "version": 1, "ir_version": 1, "generator": "mg-proto self-test",
        "cases": [
            {"name": "method", "ir": encode(eq(field("req.method"), s("GET")), &lists)},
            {"name": "owner", "ir": encode(ip_in(field("net.ip"), "owner_cidrs"), &lists)},
            {"name": "tls", "ir": encode(eq(field("tls.version"), s("TLSv1.3")), &lists)},
            {"name": "broken", "ir": encode(ip_in(field("net.ip"), "broken"), &lists)}
        ]
    });
    let dir = temp_dir("ok");
    write_fixture(&dir, cases.clone(), irs.clone());
    let report = run_suite(&dir).unwrap();
    assert!(report.failures.is_empty(), "{:?}", report.failures);
    assert_eq!(report.evaluated, 4);

    // A wrong expectation, a tampered step bound and a misordered IR file are all caught.
    let mut bad_cases = cases.clone();
    bad_cases["cases"][0]["expect"] = "false".into();
    let mut bad_irs = irs.clone();
    let mut tampered = v1::PolicyExpr::decode(
        base64::engine::general_purpose::STANDARD
            .decode(irs["cases"][1]["ir"].as_str().unwrap())
            .unwrap()
            .as_slice(),
    )
    .unwrap();
    tampered.max_steps += 1;
    bad_irs["cases"][1]["ir"] = base64::engine::general_purpose::STANDARD
        .encode(tampered.encode_to_vec())
        .into();
    bad_irs["cases"].as_array_mut().unwrap().swap(2, 3);
    let dir = temp_dir("bad");
    write_fixture(&dir, bad_cases, bad_irs);
    let report = run_suite(&dir).unwrap();
    let text = report.failures.join("\n");
    assert!(
        text.contains("method") && text.contains("expected false"),
        "{text}"
    );
    assert!(text.contains("step bound mismatch"), "{text}");
    assert!(text.contains("in order"), "{text}");

    // Typos in an Activation context are errors, not zero values.
    let mut typo = cases;
    typo["contexts"]["cf_browser"]["input"]["net"]["ipp"] = "1.2.3.4".into();
    let dir = temp_dir("typo");
    write_fixture(&dir, typo, irs);
    let report = run_suite(&dir).unwrap();
    assert!(
        report
            .failures
            .iter()
            .any(|f| f.contains("not Activation JSON"))
    );
}
